/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UploadRouteImport } from './routes/upload'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardTresorerieRouteImport } from './routes/dashboard.tresorerie'
import { Route as DashboardRevenusRouteImport } from './routes/dashboard.revenus'
import { Route as DashboardInsightsRouteImport } from './routes/dashboard.insights'
import { Route as DashboardFournisseursRouteImport } from './routes/dashboard.fournisseurs'
import { Route as DashboardClientsRouteImport } from './routes/dashboard.clients'
import { Route as DashboardChargesRouteImport } from './routes/dashboard.charges'
import { Route as DashboardBilanRouteImport } from './routes/dashboard.bilan'

const UploadRoute = UploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTresorerieRoute = DashboardTresorerieRouteImport.update({
  id: '/tresorerie',
  path: '/tresorerie',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardRevenusRoute = DashboardRevenusRouteImport.update({
  id: '/revenus',
  path: '/revenus',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardInsightsRoute = DashboardInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardFournisseursRoute = DashboardFournisseursRouteImport.update({
  id: '/fournisseurs',
  path: '/fournisseurs',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardClientsRoute = DashboardClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardChargesRoute = DashboardChargesRouteImport.update({
  id: '/charges',
  path: '/charges',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBilanRoute = DashboardBilanRouteImport.update({
  id: '/bilan',
  path: '/bilan',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/upload': typeof UploadRoute
  '/dashboard/bilan': typeof DashboardBilanRoute
  '/dashboard/charges': typeof DashboardChargesRoute
  '/dashboard/clients': typeof DashboardClientsRoute
  '/dashboard/fournisseurs': typeof DashboardFournisseursRoute
  '/dashboard/insights': typeof DashboardInsightsRoute
  '/dashboard/revenus': typeof DashboardRevenusRoute
  '/dashboard/tresorerie': typeof DashboardTresorerieRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/upload': typeof UploadRoute
  '/dashboard/bilan': typeof DashboardBilanRoute
  '/dashboard/charges': typeof DashboardChargesRoute
  '/dashboard/clients': typeof DashboardClientsRoute
  '/dashboard/fournisseurs': typeof DashboardFournisseursRoute
  '/dashboard/insights': typeof DashboardInsightsRoute
  '/dashboard/revenus': typeof DashboardRevenusRoute
  '/dashboard/tresorerie': typeof DashboardTresorerieRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/upload': typeof UploadRoute
  '/dashboard/bilan': typeof DashboardBilanRoute
  '/dashboard/charges': typeof DashboardChargesRoute
  '/dashboard/clients': typeof DashboardClientsRoute
  '/dashboard/fournisseurs': typeof DashboardFournisseursRoute
  '/dashboard/insights': typeof DashboardInsightsRoute
  '/dashboard/revenus': typeof DashboardRevenusRoute
  '/dashboard/tresorerie': typeof DashboardTresorerieRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/upload'
    | '/dashboard/bilan'
    | '/dashboard/charges'
    | '/dashboard/clients'
    | '/dashboard/fournisseurs'
    | '/dashboard/insights'
    | '/dashboard/revenus'
    | '/dashboard/tresorerie'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/upload'
    | '/dashboard/bilan'
    | '/dashboard/charges'
    | '/dashboard/clients'
    | '/dashboard/fournisseurs'
    | '/dashboard/insights'
    | '/dashboard/revenus'
    | '/dashboard/tresorerie'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/upload'
    | '/dashboard/bilan'
    | '/dashboard/charges'
    | '/dashboard/clients'
    | '/dashboard/fournisseurs'
    | '/dashboard/insights'
    | '/dashboard/revenus'
    | '/dashboard/tresorerie'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  UploadRoute: typeof UploadRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/tresorerie': {
      id: '/dashboard/tresorerie'
      path: '/tresorerie'
      fullPath: '/dashboard/tresorerie'
      preLoaderRoute: typeof DashboardTresorerieRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/revenus': {
      id: '/dashboard/revenus'
      path: '/revenus'
      fullPath: '/dashboard/revenus'
      preLoaderRoute: typeof DashboardRevenusRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/insights': {
      id: '/dashboard/insights'
      path: '/insights'
      fullPath: '/dashboard/insights'
      preLoaderRoute: typeof DashboardInsightsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/fournisseurs': {
      id: '/dashboard/fournisseurs'
      path: '/fournisseurs'
      fullPath: '/dashboard/fournisseurs'
      preLoaderRoute: typeof DashboardFournisseursRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/clients': {
      id: '/dashboard/clients'
      path: '/clients'
      fullPath: '/dashboard/clients'
      preLoaderRoute: typeof DashboardClientsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/charges': {
      id: '/dashboard/charges'
      path: '/charges'
      fullPath: '/dashboard/charges'
      preLoaderRoute: typeof DashboardChargesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/bilan': {
      id: '/dashboard/bilan'
      path: '/bilan'
      fullPath: '/dashboard/bilan'
      preLoaderRoute: typeof DashboardBilanRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardBilanRoute: typeof DashboardBilanRoute
  DashboardChargesRoute: typeof DashboardChargesRoute
  DashboardClientsRoute: typeof DashboardClientsRoute
  DashboardFournisseursRoute: typeof DashboardFournisseursRoute
  DashboardInsightsRoute: typeof DashboardInsightsRoute
  DashboardRevenusRoute: typeof DashboardRevenusRoute
  DashboardTresorerieRoute: typeof DashboardTresorerieRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardBilanRoute: DashboardBilanRoute,
  DashboardChargesRoute: DashboardChargesRoute,
  DashboardClientsRoute: DashboardClientsRoute,
  DashboardFournisseursRoute: DashboardFournisseursRoute,
  DashboardInsightsRoute: DashboardInsightsRoute,
  DashboardRevenusRoute: DashboardRevenusRoute,
  DashboardTresorerieRoute: DashboardTresorerieRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  UploadRoute: UploadRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
