/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardBilanRouteImport } from './routes/dashboard.bilan'
import { Route as DashboardChargesRouteImport } from './routes/dashboard.charges'
import { Route as DashboardClientsRouteImport } from './routes/dashboard.clients'
import { Route as DashboardFournisseursRouteImport } from './routes/dashboard.fournisseurs'
import { Route as DashboardInsightsRouteImport } from './routes/dashboard.insights'
import { Route as DashboardRevenusRouteImport } from './routes/dashboard.revenus'
import { Route as DashboardTresorerieRouteImport } from './routes/dashboard.tresorerie'
import { Route as DemoIndexRouteImport } from './routes/demo.index'
import { Route as DemoBilanRouteImport } from './routes/demo.bilan'
import { Route as DemoChargesRouteImport } from './routes/demo.charges'
import { Route as DemoClientsRouteImport } from './routes/demo.clients'
import { Route as DemoFournisseursRouteImport } from './routes/demo.fournisseurs'
import { Route as DemoInsightsRouteImport } from './routes/demo.insights'
import { Route as DemoRevenusRouteImport } from './routes/demo.revenus'
import { Route as DemoTresorerieRouteImport } from './routes/demo.tresorerie'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBilanRoute = DashboardBilanRouteImport.update({
  id: '/bilan',
  path: '/bilan',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardChargesRoute = DashboardChargesRouteImport.update({
  id: '/charges',
  path: '/charges',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardClientsRoute = DashboardClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardFournisseursRoute = DashboardFournisseursRouteImport.update({
  id: '/fournisseurs',
  path: '/fournisseurs',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardInsightsRoute = DashboardInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardRevenusRoute = DashboardRevenusRouteImport.update({
  id: '/revenus',
  path: '/revenus',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTresorerieRoute = DashboardTresorerieRouteImport.update({
  id: '/tresorerie',
  path: '/tresorerie',
  getParentRoute: () => DashboardRoute,
} as any)
const DemoIndexRoute = DemoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DemoRoute,
} as any)
const DemoBilanRoute = DemoBilanRouteImport.update({
  id: '/bilan',
  path: '/bilan',
  getParentRoute: () => DemoRoute,
} as any)
const DemoChargesRoute = DemoChargesRouteImport.update({
  id: '/charges',
  path: '/charges',
  getParentRoute: () => DemoRoute,
} as any)
const DemoClientsRoute = DemoClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => DemoRoute,
} as any)
const DemoFournisseursRoute = DemoFournisseursRouteImport.update({
  id: '/fournisseurs',
  path: '/fournisseurs',
  getParentRoute: () => DemoRoute,
} as any)
const DemoInsightsRoute = DemoInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => DemoRoute,
} as any)
const DemoRevenusRoute = DemoRevenusRouteImport.update({
  id: '/revenus',
  path: '/revenus',
  getParentRoute: () => DemoRoute,
} as any)
const DemoTresorerieRoute = DemoTresorerieRouteImport.update({
  id: '/tresorerie',
  path: '/tresorerie',
  getParentRoute: () => DemoRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/demo': typeof DemoRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/dashboard/bilan': typeof DashboardBilanRoute
  '/dashboard/charges': typeof DashboardChargesRoute
  '/dashboard/clients': typeof DashboardClientsRoute
  '/dashboard/fournisseurs': typeof DashboardFournisseursRoute
  '/dashboard/insights': typeof DashboardInsightsRoute
  '/dashboard/revenus': typeof DashboardRevenusRoute
  '/dashboard/tresorerie': typeof DashboardTresorerieRoute
  '/demo/bilan': typeof DemoBilanRoute
  '/demo/charges': typeof DemoChargesRoute
  '/demo/clients': typeof DemoClientsRoute
  '/demo/fournisseurs': typeof DemoFournisseursRoute
  '/demo/insights': typeof DemoInsightsRoute
  '/demo/revenus': typeof DemoRevenusRoute
  '/demo/tresorerie': typeof DemoTresorerieRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/demo/': typeof DemoIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/dashboard/bilan': typeof DashboardBilanRoute
  '/dashboard/charges': typeof DashboardChargesRoute
  '/dashboard/clients': typeof DashboardClientsRoute
  '/dashboard/fournisseurs': typeof DashboardFournisseursRoute
  '/dashboard/insights': typeof DashboardInsightsRoute
  '/dashboard/revenus': typeof DashboardRevenusRoute
  '/dashboard/tresorerie': typeof DashboardTresorerieRoute
  '/demo/bilan': typeof DemoBilanRoute
  '/demo/charges': typeof DemoChargesRoute
  '/demo/clients': typeof DemoClientsRoute
  '/demo/fournisseurs': typeof DemoFournisseursRoute
  '/demo/insights': typeof DemoInsightsRoute
  '/demo/revenus': typeof DemoRevenusRoute
  '/demo/tresorerie': typeof DemoTresorerieRoute
  '/dashboard': typeof DashboardIndexRoute
  '/demo': typeof DemoIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/demo': typeof DemoRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/dashboard/bilan': typeof DashboardBilanRoute
  '/dashboard/charges': typeof DashboardChargesRoute
  '/dashboard/clients': typeof DashboardClientsRoute
  '/dashboard/fournisseurs': typeof DashboardFournisseursRoute
  '/dashboard/insights': typeof DashboardInsightsRoute
  '/dashboard/revenus': typeof DashboardRevenusRoute
  '/dashboard/tresorerie': typeof DashboardTresorerieRoute
  '/demo/bilan': typeof DemoBilanRoute
  '/demo/charges': typeof DemoChargesRoute
  '/demo/clients': typeof DemoClientsRoute
  '/demo/fournisseurs': typeof DemoFournisseursRoute
  '/demo/insights': typeof DemoInsightsRoute
  '/demo/revenus': typeof DemoRevenusRoute
  '/demo/tresorerie': typeof DemoTresorerieRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/demo/': typeof DemoIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/demo'
    | '/onboarding'
    | '/dashboard/bilan'
    | '/dashboard/charges'
    | '/dashboard/clients'
    | '/dashboard/fournisseurs'
    | '/dashboard/insights'
    | '/dashboard/revenus'
    | '/dashboard/tresorerie'
    | '/demo/bilan'
    | '/demo/charges'
    | '/demo/clients'
    | '/demo/fournisseurs'
    | '/demo/insights'
    | '/demo/revenus'
    | '/demo/tresorerie'
    | '/dashboard/'
    | '/demo/'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/onboarding'
    | '/dashboard/bilan'
    | '/dashboard/charges'
    | '/dashboard/clients'
    | '/dashboard/fournisseurs'
    | '/dashboard/insights'
    | '/dashboard/revenus'
    | '/dashboard/tresorerie'
    | '/demo/bilan'
    | '/demo/charges'
    | '/demo/clients'
    | '/demo/fournisseurs'
    | '/demo/insights'
    | '/demo/revenus'
    | '/demo/tresorerie'
    | '/dashboard'
    | '/demo'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/dashboard'
    | '/demo'
    | '/onboarding'
    | '/dashboard/bilan'
    | '/dashboard/charges'
    | '/dashboard/clients'
    | '/dashboard/fournisseurs'
    | '/dashboard/insights'
    | '/dashboard/revenus'
    | '/dashboard/tresorerie'
    | '/demo/bilan'
    | '/demo/charges'
    | '/demo/clients'
    | '/demo/fournisseurs'
    | '/demo/insights'
    | '/demo/revenus'
    | '/demo/tresorerie'
    | '/dashboard/'
    | '/demo/'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  DemoRoute: typeof DemoRouteWithChildren
  OnboardingRoute: typeof OnboardingRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/bilan': {
      id: '/dashboard/bilan'
      path: '/bilan'
      fullPath: '/dashboard/bilan'
      preLoaderRoute: typeof DashboardBilanRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/charges': {
      id: '/dashboard/charges'
      path: '/charges'
      fullPath: '/dashboard/charges'
      preLoaderRoute: typeof DashboardChargesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/clients': {
      id: '/dashboard/clients'
      path: '/clients'
      fullPath: '/dashboard/clients'
      preLoaderRoute: typeof DashboardClientsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/fournisseurs': {
      id: '/dashboard/fournisseurs'
      path: '/fournisseurs'
      fullPath: '/dashboard/fournisseurs'
      preLoaderRoute: typeof DashboardFournisseursRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/insights': {
      id: '/dashboard/insights'
      path: '/insights'
      fullPath: '/dashboard/insights'
      preLoaderRoute: typeof DashboardInsightsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/revenus': {
      id: '/dashboard/revenus'
      path: '/revenus'
      fullPath: '/dashboard/revenus'
      preLoaderRoute: typeof DashboardRevenusRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/tresorerie': {
      id: '/dashboard/tresorerie'
      path: '/tresorerie'
      fullPath: '/dashboard/tresorerie'
      preLoaderRoute: typeof DashboardTresorerieRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/demo/': {
      id: '/demo/'
      path: '/'
      fullPath: '/demo/'
      preLoaderRoute: typeof DemoIndexRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/bilan': {
      id: '/demo/bilan'
      path: '/bilan'
      fullPath: '/demo/bilan'
      preLoaderRoute: typeof DemoBilanRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/charges': {
      id: '/demo/charges'
      path: '/charges'
      fullPath: '/demo/charges'
      preLoaderRoute: typeof DemoChargesRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/clients': {
      id: '/demo/clients'
      path: '/clients'
      fullPath: '/demo/clients'
      preLoaderRoute: typeof DemoClientsRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/fournisseurs': {
      id: '/demo/fournisseurs'
      path: '/fournisseurs'
      fullPath: '/demo/fournisseurs'
      preLoaderRoute: typeof DemoFournisseursRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/insights': {
      id: '/demo/insights'
      path: '/insights'
      fullPath: '/demo/insights'
      preLoaderRoute: typeof DemoInsightsRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/revenus': {
      id: '/demo/revenus'
      path: '/revenus'
      fullPath: '/demo/revenus'
      preLoaderRoute: typeof DemoRevenusRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/tresorerie': {
      id: '/demo/tresorerie'
      path: '/tresorerie'
      fullPath: '/demo/tresorerie'
      preLoaderRoute: typeof DemoTresorerieRouteImport
      parentRoute: typeof DemoRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardRouteChildren {
  DashboardBilanRoute: typeof DashboardBilanRoute
  DashboardChargesRoute: typeof DashboardChargesRoute
  DashboardClientsRoute: typeof DashboardClientsRoute
  DashboardFournisseursRoute: typeof DashboardFournisseursRoute
  DashboardInsightsRoute: typeof DashboardInsightsRoute
  DashboardRevenusRoute: typeof DashboardRevenusRoute
  DashboardTresorerieRoute: typeof DashboardTresorerieRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardBilanRoute: DashboardBilanRoute,
  DashboardChargesRoute: DashboardChargesRoute,
  DashboardClientsRoute: DashboardClientsRoute,
  DashboardFournisseursRoute: DashboardFournisseursRoute,
  DashboardInsightsRoute: DashboardInsightsRoute,
  DashboardRevenusRoute: DashboardRevenusRoute,
  DashboardTresorerieRoute: DashboardTresorerieRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface DemoRouteChildren {
  DemoBilanRoute: typeof DemoBilanRoute
  DemoChargesRoute: typeof DemoChargesRoute
  DemoClientsRoute: typeof DemoClientsRoute
  DemoFournisseursRoute: typeof DemoFournisseursRoute
  DemoInsightsRoute: typeof DemoInsightsRoute
  DemoRevenusRoute: typeof DemoRevenusRoute
  DemoTresorerieRoute: typeof DemoTresorerieRoute
  DemoIndexRoute: typeof DemoIndexRoute
}

const DemoRouteChildren: DemoRouteChildren = {
  DemoBilanRoute: DemoBilanRoute,
  DemoChargesRoute: DemoChargesRoute,
  DemoClientsRoute: DemoClientsRoute,
  DemoFournisseursRoute: DemoFournisseursRoute,
  DemoInsightsRoute: DemoInsightsRoute,
  DemoRevenusRoute: DemoRevenusRoute,
  DemoTresorerieRoute: DemoTresorerieRoute,
  DemoIndexRoute: DemoIndexRoute,
}

const DemoRouteWithChildren = DemoRoute._addFileChildren(DemoRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRouteWithChildren,
  DemoRoute: DemoRouteWithChildren,
  OnboardingRoute: OnboardingRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
